"""PDF report generator for EU AI Act risk assessment results."""
from __future__ import annotations

import os
import tempfile
from datetime import datetime

from fpdf import FPDF

RISK_COLORS = {
    "禁止": (220, 50, 50),
    "Prohibited": (220, 50, 50),
    "高リスク": (200, 60, 60),
    "High-Risk": (200, 60, 60),
    "透明性": (220, 120, 30),
    "Transparency": (220, 120, 30),
    "限定": (200, 160, 30),
    "Limited": (200, 160, 30),
}

FONT_DIR = os.path.join(os.path.dirname(__file__), "fonts")
NOTO_REGULAR = os.path.join(FONT_DIR, "NotoSansJP-Regular.ttf")
NOTO_BOLD = os.path.join(FONT_DIR, "NotoSansJP-Bold.ttf")


def _ensure_fonts() -> bool:
    """Download Noto Sans JP fonts if not present. Returns True if available."""
    if os.path.exists(NOTO_REGULAR) and os.path.exists(NOTO_BOLD):
        return True
    os.makedirs(FONT_DIR, exist_ok=True)
    try:
        import urllib.request
        base = "https://github.com/google/fonts/raw/main/ofl/notosansjp/"
        urllib.request.urlretrieve(base + "NotoSansJP%5Bwght%5D.ttf", NOTO_REGULAR)
        import shutil
        shutil.copy(NOTO_REGULAR, NOTO_BOLD)
        return True
    except Exception:
        return False


def _get_risk_color(level: str) -> tuple[int, int, int]:
    for key, color in RISK_COLORS.items():
        if key in level:
            return color
    return (40, 140, 60)


class RiskReportPDF(FPDF):
    def __init__(self, has_japanese_font: bool):
        super().__init__()
        self._has_jp = has_japanese_font

    def set_font_jp(self, style: str = "", size: int = 11):
        if self._has_jp:
            self.set_font("NotoJP", style=style, size=size)
        else:
            self.set_font("Helvetica", style=style, size=size)

    def header(self):
        self.set_fill_color(15, 76, 129)
        self.rect(0, 0, 210, 18, "F")
        self.set_text_color(255, 255, 255)
        self.set_font_jp(size=11)
        self.set_y(4)
        self.cell(0, 10, "Agentic AI Risk Assessment Report  |  EU AI Act (Regulation (EU) 2024/1689)", align="C")
        self.set_text_color(0, 0, 0)
        self.ln(14)

    def footer(self):
        self.set_y(-14)
        self.set_text_color(130, 130, 130)
        self.set_font_jp(size=8)
        self.cell(0, 10, f"Page {self.page_no()}  |  Generated by Agentic AI Risk Assessment Tool", align="C")
        self.set_text_color(0, 0, 0)

    def section_title(self, title: str):
        self.set_fill_color(230, 240, 250)
        self.set_font_jp(size=11)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT", fill=True)
        self.ln(2)

    def label_value(self, label: str, value: str):
        self.set_font_jp(size=9)
        self.set_text_color(80, 80, 80)
        self.multi_cell(0, 6, label, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.set_font_jp(size=10)
        self.set_left_margin(18)
        self.multi_cell(0, 6, value or "—", new_x="LMARGIN", new_y="NEXT")
        self.set_left_margin(12)
        self.ln(2)


def generate_pdf(
    risk_level: str,
    risk_basis: str,
    overview: str,
    users: str,
    data_subjects: str,
    input_cats: str,
    output_cats: str,
    purposes: str,
    eu_ai_act_url: str,
) -> str:
    """Generate a PDF report and return the file path."""
    has_jp = _ensure_fonts()

    pdf = RiskReportPDF(has_japanese_font=has_jp)
    if has_jp:
        pdf.add_font("NotoJP", style="", fname=NOTO_REGULAR)
        pdf.add_font("NotoJP", style="B", fname=NOTO_BOLD)

    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(left=12, top=22, right=12)
    pdf.add_page()

    now_str = datetime.now().strftime("%Y年%m月%d日 %H:%M")

    # ── Title block ──────────────────────────────────────────────────────────
    pdf.set_font_jp(size=16)
    pdf.cell(0, 10, "EU AI Act リスク評価レポート", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font_jp(size=9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"評価日時: {now_str}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    # ── Risk level badge ─────────────────────────────────────────────────────
    r, g, b = _get_risk_color(risk_level)
    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font_jp(size=14)
    pdf.cell(0, 14, f"  リスクレベル: {risk_level}", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    # ── Application information ───────────────────────────────────────────────
    pdf.section_title("1. アプリケーション情報")
    fields = [
        ("2-1. 概要説明文", overview),
        ("2-2. アプリケーション利用者", users),
        ("2-3. 入力情報の主体（Data Subject）", data_subjects),
        ("2-4. 入力情報の情報種（情報カテゴリ）", input_cats),
        ("2-5. 出力情報の情報種（情報カテゴリ）", output_cats),
        ("2-6. 出力情報の利用目的", purposes),
    ]
    for label, value in fields:
        pdf.label_value(label, value)

    pdf.ln(3)

    # ── Risk basis ────────────────────────────────────────────────────────────
    pdf.section_title("2. 判定根拠（EU AI Act 条文参照）")
    pdf.set_font_jp(size=10)
    pdf.multi_cell(0, 6, risk_basis or "—", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Source note ───────────────────────────────────────────────────────────
    pdf.set_draw_color(200, 200, 200)
    pdf.set_line_width(0.3)
    pdf.line(12, pdf.get_y(), 198, pdf.get_y())
    pdf.ln(3)
    pdf.set_font_jp(size=8)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(
        0,
        5,
        (
            "判定根拠: EU AI Act公式PDFから構築したRAGベクトルデータベースの検索結果のみを使用\n"
            f"出典: {eu_ai_act_url}"
        ),
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.set_text_color(0, 0, 0)

    tmp = tempfile.NamedTemporaryFile(
        suffix=".pdf",
        prefix="eu_ai_act_risk_report_",
        delete=False,
    )
    tmp.close()
    pdf.output(tmp.name)
    return tmp.name
